### ISSUE TITLE
Our projects - sidebar top component flickers during transitions

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#223] opened 2017-07-04 04:38 UTC

**Comment by mihai-macaneata** [comment] 2017-07-04 08:42
Can't reproduce locally

**Comment by xlotlu** [comment] 2017-07-07 08:57
possibly related to (or duplicate of) https://github.com/EEA-Norway-Grants/dataviz/issues/200

**Closed** 2017-08-14 03:14 UTC
Labels: Status: Blocked, Type: minor Bug
