### ISSUE TITLE
Embedding: various issues

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#440] opened 2017-10-04 13:34 UTC
possibly related to 30be6da75ac93b15ea856aa583b1249189ea5cd0

**Comment by melish** [comment] 2017-10-05 08:36
- [ ] tooltip css missing
- [ ] project count (red bubbles) not visible on the project map
- [ ] arcs not visible on the partnership map
- [ ] ajax not working on the project map (#319)


Embedding can be tested in the main website, under:
https://eeagrants.org/Results-data/Results-overview
https://eeagrants.org/Partnerships
https://eeagrants.org/


(search for ".snippet-test" class in the code inspect and remove "display: none" attribute )

**Comment by xlotlu** [comment] 2017-10-09 09:25
closing this because issues 2, 3, and 5 are caused by the embedded components being initialised with `display: none`, which is neither expected usage, nor a likely future requirement.

writing code to deal with this scenario is exceedingly complicated, and would involve either [mutation events](https://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-eventgroupings-mutationevents) or the experimental [intersection observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). remote should set up a proper testing environment instead.

#319 is tracked separately, with priority: high.

**Closed by xlotlu** 2017-10-09 09:25 UTC
Labels: Priority: High, Type: Bug
