### ISSUE TITLE
page trembling when removing BS filter

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#200] opened 2017-06-26 15:50 UTC
![such beauty](https://user-images.githubusercontent.com/136097/27547855-e74a4ec4-5a9f-11e7-9172-76383ecee890.gif)

**Comment by mihai-macaneata** [comment] 2017-07-20 13:13
Can't reproduce

**Comment by mihai-macaneata** [comment] 2017-08-11 09:48
fixed in 652a7c32122a4e702cfdaaddc6241be9ad4b4b0e

**Closed by mihai-macaneata** 2017-08-11 09:48 UTC
Labels: Status: Blocked, Type: Bug
